meal_planner/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("meal_plans.urls")),
    path("users/", include("users.urls"))
]

meal_plans/urls.py
from django.urls import path
from . import views
from .views import search_view

app_name = "meal_plans"

urlpatterns = [
    path("", views.index, name="index"),
    path('meal_plans/', views.meal_plan_list, name='meal_plan_list'),
    path('meal_plans/<int:pk>/', views.meal_plan_detail, name='meal_plan_detail'),
    path('meal_plans/create/', views.meal_plan_create, name='meal_plan_create'),
    path('meal_plans/<int:pk>/update/', views.meal_plan_update, name='meal_plan_update'),
    path('meal_plans/<int:pk>/delete/', views.meal_plan_delete, name='meal_plan_delete'),
    path('meal_plans/<int:meal_plan_id>/add_meal/', views.add_meal, name='add_meal'),
    path('meal_plans/meal_list/', views.meal_list_view, name="meal_list"),
    path('meal_plans/meal/update/<int:meal_id>/', views.meal_update, name='meal_update'),
    path('meal_plans/meal/delete/<int:meal_id>/', views.meal_delete, name='meal_delete'),
    path('meal_plans/<int:meal_id>/recipe/create/', views.recipe_create, name='recipe_create'),
    path('meal_plans/<int:recipe_id>/recipe/update/', views.recipe_update, name='recipe_update'),
    path('meal_plans/<int:recipe_id>/recipe/delete/', views.recipe_delete, name='recipe_delete'),
    path('recipes/<int:recipe_id>/', views.recipe_detail, name='recipe_detail'),
    path('search/', search_view, name='search'),

]


















# urlpatterns = [
    #   path("", views.index, name="index"),
    # path('meal_plans/', views.meal_plan_list, name='meal_plan_list'),
    # path('meal_plans/create/', views.meal_plan_create, name='meal_plan_create'),
    # path('meal_plans/<int:pk>/', views.meal_plan_detail, name='meal_plan_detail'),
    # path('meal_plans/<int:pk>/update/', views.meal_plan_update, name='meal_plan_update'),
    # path('meal_plans/<int:pk>/delete/', views.meal_plan_delete, name='meal_plan_delete'),
    # path('meal_plans/<int:pk>/add_meal/', views.add_meal, name='add_meal'),
    # path('meal_plans/meal_list', views.meal_list_view, name="meal_list"),
    # path('meal_plans/<int:meal_plan_id>/recipe/create/', views.recipe_create, name='recipe_create'),
    # path('recipes/<int:meal_plan_id>/', views.recipe_detail, name='recipe_detail'),
    # path('search/', search_view, name='search'),
#     path('meal_plans/meal/update/<int:meal_id>/', views.meal_update, name='meal_update'),
#     path('meal_plans/meal/delete/<int:meal_id>/', views.meal_delete, name='meal_delete'),
#     path('meal_plans/<int:meal_plan_id>/recipe/update/', views.recipe_update, name='recipe_update'),
#     path('meal_plans/<int:meal_plan_id>/recipe/delete/', views.recipe_delete, name='recipe_delete'),
# ]

users/urls.py
from django.urls import path, include
from . import views

app_name = "users"
urlpatterns = [
    # include the defaults urls
    # path('', include('django.contrib.auth.urls')),
    path("login/", views.user_login, name="login"),
    path("register/", views.register, name="register"),
    path('profile/', views.profile_view, name='profile'),
    path('logout/', views.logout_view, name='logout'),

]

meal_plans/models.py
from django.db import models
from django.contrib.auth.models import User


class MealPlan(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    start_date = models.DateField()
    end_date = models.DateField()
    def __str__(self):
        return self.name

class Meal(models.Model):
    MEAL_CHOICES = [
        ('breakfast', 'Breakfast'),
        ('lunch', 'Lunch'),
        ('dinner', 'Dinner'),
    ]
    
    meal_plan = models.ForeignKey(MealPlan, on_delete=models.CASCADE)
    meal_name = models.CharField(max_length=200)
    meal_time = models.CharField(max_length=20, choices=MEAL_CHOICES)
    date_added = models.DateField()



    def __str__(self):
        return self.meal_name

class Recipe(models.Model):
    meal = models.ForeignKey(Meal, on_delete=models.CASCADE, related_name='recipe')
    ingredients = models.TextField()
    instructions = models.TextField()



    def __str__(self):
        return f"Recipe for {self.meal}"

meal_plans/forms.py
from django import forms
from .models import MealPlan, Meal, Recipe

class MealPlanForm(forms.ModelForm):
    
    start_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    end_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))



    class Meta:
        model = MealPlan
        fields = ['name', 'start_date', 'end_date']

class MealForm(forms.ModelForm):
    date_added = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    
    class Meta:
        model = Meal
        fields = ['meal_name', 'meal_time', 'date_added']




class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ['meal', 'ingredients', 'instructions']

meal_plans/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .forms import MealPlanForm, MealForm, RecipeForm
from .models import MealPlan, Meal, Recipe
import requests
from itertools import groupby
from operator import attrgetter
import datetime
import environ

# environment variable
env = environ.Env()
environ.Env.read_env()



def index(request):
    # index page
    return render(request, "meal_plans/index.html")

@login_required
def meal_plan_list(request):
    # get all plans
    meal_plans = MealPlan.objects.filter(user=request.user)
    context = {'meal_plans': meal_plans}
    return render(request, 'meal_plans/meal_plan_list.html', context)


@login_required
def meal_plan_detail(request, pk):
    # get all meals
    meal_plan = get_object_or_404(MealPlan, pk=pk, user=request.user)
    meals = meal_plan.meal_set.all()
    now = datetime.date.today()
    context = {'meal_plan': meal_plan, 'meals': meals, "now": now,}
    return render(request, 'meal_plans/meal_plan_detail.html', context)


@login_required
def meal_plan_create(request):
    """
    creating a meal plan and attached it to the user
    that own the data.
    """
    if request.method == 'POST':
        form = MealPlanForm(request.POST)
        if form.is_valid():
            meal_plan = form.save(commit=False)
            meal_plan.user = request.user
            meal_plan.save()
            return redirect('meal_plans:meal_plan_detail', pk=meal_plan.pk)
    else:
        form = MealPlanForm()
    context = {'form': form}
    return render(request, 'meal_plans/meal_plan_create.html', context)


@login_required
def meal_plan_update(request, pk):
    """
    updating the meal plan
    """
    meal_plan = get_object_or_404(MealPlan, pk=pk, user=request.user)
    if request.method == 'POST':
        form = MealPlanForm(request.POST, instance=meal_plan)
        if form.is_valid():
            form.save()
            return redirect('meal_plans:meal_plan_detail', pk=meal_plan.pk)
    else:
        form = MealPlanForm(instance=meal_plan)
    context = {'form': form, 'meal_plan': meal_plan}
    return render(request, 'meal_plans/meal_plan_update.html', context)


@login_required
def meal_plan_delete(request, pk):
    """
    updating a meal base on the request of the user
    """
    meal_plan = get_object_or_404(MealPlan, pk=pk, user=request.user)
    if request.method == 'POST':
        meal_plan.delete()
        return redirect('meal_plans:meal_plan_list')
    context = {'meal_plan': meal_plan}
    return render(request, 'meal_plans/meal_plan_delete.html', context)


@login_required
def add_meal(request, meal_plan_id):
    """
    add a meal to the meal plan
    """
    meal_plan = get_object_or_404(MealPlan, pk=meal_plan_id, user=request.user)
    if request.method == 'POST':
        form = MealForm(request.POST)
        if form.is_valid():
            meal = form.save(commit=False)
            meal.meal_plan = meal_plan
            meal.save()
            return redirect('meal_plans:meal_plan_detail', pk=meal_plan.pk)
    else:
        form = MealForm()
    context = {'form': form, 'meal_plan': meal_plan}
    return render(request, 'meal_plans/add_meal.html', context)



@login_required
def meal_list_view(request):
    """
    The view is meant to meal list added by the user
    """

    meals = Meal.objects.filter(meal_plan__user=request.user)

    meal_groups =[]

    for date, meals_in_date in groupby(meals, key=attrgetter('date_added')):
        meal_group = {
            'date': date,
            'meals': list(meals_in_date)
        }
        meal_groups.append(meal_group)
    
    context = {
        'meal_groups': meal_groups,
        'all_meals': meals
    }
    return render(request, 'meal_plans/meal_list.html', context)



@login_required
def meal_update(request, meal_id):
    """
    updating the meal added by the user
    """
    meal = get_object_or_404(Meal, pk=meal_id, meal_plan__user=request.user)
    if request.method == 'POST':
        form = MealForm(request.POST, instance=meal)
        if form.is_valid():
            form.save()
            return redirect('meal_plans:meal_list')
    else:
        form = MealForm(instance=meal)
    context = {'form': form, 'meal': meal}
    return render(request, 'meal_plans/meal_update.html', context)


@login_required
def meal_delete(request, meal_id):
    """
    deleting a meal base on the request of the user
    """
    meal = get_object_or_404(Meal, pk=meal_id, meal_plan__user=request.user)
    if request.method == 'POST':
        meal.delete()
        return redirect('meal_plans:meal_list')
    context = {'meal': meal}
    return render(request, 'meal_plans/meal_delete.html', context)


@login_required
def recipe_create(request, meal_id):
    """
    create recipe base on the meal added by the user
    """
    meal = get_object_or_404(Meal, pk=meal_id, meal_plan__user=request.user)
    if request.method == 'POST':
        form = RecipeForm(request.POST)
        if form.is_valid():
            recipe = form.save(commit=False)
            recipe.meal = meal
            recipe.save()
            return redirect('meal_plans:recipe_detail', recipe_id=recipe.id)
    else:
        form = RecipeForm()
    context = {'form': form, 'meal': meal}
    return render(request, 'meal_plans/recipe_create.html', context)



@login_required
def recipe_update(request, recipe_id):
    """
    updating the recipe entered by the user
    """
    recipe = get_object_or_404(Recipe, pk=recipe_id )

    if request.method == 'POST':
        form = RecipeForm(request.POST, instance=recipe)
        if form.is_valid():
            form.save()
            return redirect('meal_plans:recipe_detail', recipe_id=recipe.id)
    else:
        form = RecipeForm(instance=recipe)

    context = {
        'form': form,
        'recipe': recipe
    }
    return render(request, 'meal_plans/recipe_update.html', context)



@login_required
def recipe_delete(request, recipe_id):
    """
    deleting a recipe entred by the user
    """
    recipe = get_object_or_404(Recipe, id=recipe_id)

    if request.method == 'POST':
        recipe.delete()
        return redirect('meal_plans:meal_list')

    context = {
        'recipe': recipe
    }
    return render(request, 'meal_plans/recipe_delete.html', context)


@login_required
def recipe_detail(request, recipe_id):
    """
    shows the details entered by the user
    """
    recipe = get_object_or_404(Recipe, id=recipe_id)
    
    context = {
        'recipe': recipe
    }
    
    return render(request, 'meal_plans/recipe_detail.html', context)



def search_recipe(request):
    """
    This views performs search operation perform by the user
    """
    url =f"https://api.edamam.com/api/recipes/v2?type=public&q={request}&app_id={env('app_id')}&app_key={env('app_key')}"

    response = requests.get(url)
    print(response)
    data = response.json()
    # Parse the response and extract the search results
    results = data.get('hits', [])
    return results


def search_view(request):
    """
    shows the search perform by the user 
    """
    if request.method == 'GET':
        query = request.GET.get('query')
        if query:
            # Call the search_recipe function with the query parameter
            results = search_recipe(query)
            for result in results:
                if result["recipe"].get("label") == query:
                    return render(request, 'meal_plans/search.html', {'result': result})
                else:
                    return render(request, 'meal_plans/search.html', {'results': results})
                    
    return render(request, 'meal_plans/search.html')

















































































































































































































# from django.shortcuts import render, redirect, get_object_or_404
# from .models import MealPlan, Meal,Recipe
# from .forms import MealPlanForm, MealForm, RecipeForm
# from django.contrib.auth.decorators import login_required
# from py_edamam import Recipe
# import requests
# from itertools import groupby
# from operator import attrgetter



# def index(request):
#     return render(request, "meal_plans/index.html")

# @login_required
# def meal_plan_list(request):
#     meal_plans = MealPlan.objects.filter(user=request.user)
#     context = {'meal_plans': meal_plans}
#     return render(request, 'meal_plans/meal_plan_list.html', context)


# @login_required
# def meal_plan_detail(request, pk):
#     meal_plan = MealPlan.objects.get(pk=pk, user=request.user)
#     context = {'meal_plan': meal_plan}
#     return render(request, 'meal_plans/meal_plan_detail.html', context)



# @login_required
# def meal_plan_create(request):
#     if request.method == 'POST':
#         form = MealPlanForm(request.POST)
#         if form.is_valid():
#             meal_plan = form.save(commit=False)
#             meal_plan.user = request.user
#             meal_plan.save()
#             return redirect('meal_plans:meal_plan_list')
#     else:
#         form = MealPlanForm()
#     context = {'form': form}
#     return render(request, 'meal_plans/meal_plan_create.html', context)


# @login_required
# def meal_plan_update(request, pk):
#     meal_plan = MealPlan.objects.get(pk=pk, user=request.user)
#     if request.method == 'POST':
#         form = MealPlanForm(request.POST, instance=meal_plan)
#         if form.is_valid():
#             form.save()
#             return redirect('meal_plans:meal_plan_list')
#     else:
#         form = MealPlanForm(instance=meal_plan)
#     context = {'form': form, 'meal_plan': meal_plan}
#     return render(request, 'meal_plans/meal_plan_update.html', context)



# @login_required
# def meal_plan_delete(request, pk):
#     meal_plan = MealPlan.objects.get(pk=pk, user=request.user)

meal_plans/templates/meal_plans/add_meal.html
{% extends 'meal_plans/base.html' %} {% block page_header %}

<div class="row p-4">
  <div class="bg-dark text-white p-3 mb-5 text-center">
    <h2>Add Meal</h2>
  </div>

  {% endblock page_header %} {% block content %} {% load bootstrap5 %}
  <div class="col">
    <form method="post" class="form-control p-3">
      {% csrf_token %} {% bootstrap_form form %}
      <div class="d-flex justify-content-between">
        <button type="submit" class="btn btn-outline-dark">Add Meal</button>
        <a
          href="{%  url 'meal_plans:search' %}"
          class="btn btn-outline-dark d-block"
          >Search meal</a
        >
      </div>
    </form>
  </div>
</div>
{% endblock %}

meal_plans/templates/meal_plans/index.html
{% extends "meal_plans/base.html" %} {% block content %} {% endblock content %}

meal_plans/templates/meal_plans/meal_delete.html
{% extends 'meal_plans/base.html' %} {% block page_header %}
<div class="pb-2 mb-2 border-bottom p-5 bg-dark text-white rounded mt-4">
  <h2>Delete Meal</h2>
</div>
{% endblock page_header %} {% block content %} {% load bootstrap5 %}

<p>Are you sure you want to delete the meal {{ meal.meal_name }}?</p>

<form
  method="post"
  class="tex-center"
  action="{% url 'meal_plans:meal_delete' meal.id %}"
>
  {% csrf_token %}
  <button type="submit" class="btn btn-md btn-info">Delete</button>
  <a href="{% url 'meal_plans:meal_list'%}" class="btn btn-secondary">Cancel</a>
</form>
{% endblock content %}

meal_plans/templates/meal_plans/meal_list.html
{% extends 'meal_plans/base.html' %} {% block page_header %}
<div class="container">
  <div class="row text-center pb-2 bg-dark text-white mb-5">
    <h1>Meal Info</h1>
  </div>

  <div class="row">
    {% endblock page_header %} {% block content %} {% if meal_groups %}
    <table class="table table-hover table-dark pb-3">
      <thead>
        <tr>
          <th scope="col">Date</th>
          <th scope="col">Breakfast</th>
          <th scope="col">Lunch</th>
          <th scope="col">Dinner</th>
        </tr>
      </thead>
      <tbody>
        {% for meals in meal_groups %}
        <tr>
          <th scope="row">{{ meals.date }}</th>
          {% for meal in meals.meals %}
          <td>{{ meal }}</td>
          {% endfor %}
        </tr>

        {% endfor %}
      </tbody>
    </table>

    {% else %}
    <p>No meals found.</p>
    {% endif %}
    <div class="d-flex justify-content-between">
      <a
        href="{% url 'meal_plans:meal_plan_create' %}"
        class="btn btn-outline-dark"
        >Create New Meal Plan</a
      >
      <a
        href="{% url 'meal_plans:meal_plan_list' %}"
        class="btn btn-outline-dark"
        >Back to Meal Plan</a
      >
    </div>
  </div>
</div>

{% endblock %}

meal_plans/templates/meal_plans/meal_plan_create.html
{% extends 'meal_plans/base.html' %} {% block page_header %}

<div class="row bg-dark">
  <div class="col bg-success p-5">
    <div class="p-3 bg-dark text-white text-center mb-5">
      <h2>Create a Meal Plan</h2>
    </div>
    {% endblock page_header %} {% block content %} {% load bootstrap5 %}
    <form
      method="post"
      class="form-control p-5 mb-5"
      action="{% url 'meal_plans:meal_plan_create' %}"
    >
      {% csrf_token %} {% bootstrap_form form %}
      <button type="submit" class="btn btn-outline-dark d-block w-200">
        Create
      </button>
    </form>
    {% endblock %}
  </div>
</div>

meal_plans/templates/meal_plans/meal_plan_delete.html
{% extends 'meal_plans/base.html' %} {% block page_header %}

<div class="pb-2 mb-5 border-bottom p-3 bg-dark text-white rounded mt-4">
  <h2>Delete Meal Plan</h2>
</div>
{% endblock page_header %} {% block content %}
<p class="text-light">
  Are you sure you want to delete the meal plan "{{ meal_plan.name }}"?
</p>
<form method="post">
  {% csrf_token %}
  <button type="submit" class="btn btn-dark ml-2">Delete</button>
  <a
    href="{% url 'meal_plans:meal_plan_detail' meal_plan.id %}"
    class="btn mr-5 btn-dark"
    >Cancel</a
  >
</form>
{% endblock %}

meal_plans/templates/meal_plans/meal_plan_detail.html
{% extends 'meal_plans/base.html' %} {% block page_header %}

<div class="row p-4">
  <div class="border-bottom bg-dark text-white text-center p-2 mb-2">
    <h2>Meal Plan Details</h2>
  </div>
</div>

{% endblock page_header %} {% block content %}

<div class="row p-3">
  <div class="col bg-light p-3 mb-3">
    <p>Meal Plan: {{ meal_plan.name }}</p>
    <p>Start Date: {{ meal_plan.start_date }}</p>
    <p>End Date: {{ meal_plan.end_date }}</p>
  </div>
</div>
{% if meal_plan %}
<div class="row p-3">
  {% for meal in meal_plan.meal_set.all %}
  <div class="col-md-4 bg-light mb-3 ml-3 p-3">
    <div>
      <h3>Meal details</h3>
    </div>
    <div class="mb-5">
      <h4>Meal Name: {{ meal.meal_name }} </h4>

      <h4>Meal Time: {{ meal.meal_time }} </h4>

      <h3>Date Added: {{ meal.date_added }}</span></h3>
    </div>
    <div class="d-flex justify-content-between">
      <a
        href="{% url 'meal_plans:recipe_create'  meal_id=meal.id %}"
        class="btn btn-outline-dark"
        >Add Recipe</a
      >
      <a
        href="{% url 'meal_plans:meal_update'  meal_id=meal.id %}"
        class="btn btn-outline-dark"
        >Update Meal</a
      >
      <a
        href="{% url 'meal_plans:meal_delete'  meal_id=meal.id %}"
        class="btn btn-outline-dark"
        >Delete Meal</a
      >
    </div>
  </div>
  {% endfor %}

   <div>
   
    <a
      href="{% url 'meal_plans:add_meal' meal_plan_id=meal_plan.id %}"
      class="btn btn-outline-light"
      >Add Meal</a
    >
   </div>

</div>
{% else %}

{% endif %}
{% endblock content %}

meal_plans/templates/meal_plans/meal_plan_list.html
{% extends 'meal_plans/base.html' %} {% block page_header %}
<div class="row mt-2 p-2 bg-dark text-white rounded">
  <h1>Meal Plans</h1>
  <p>Here are the list of plans you added</p>
</div>
{% endblock page_header %} {% block content %} {% if meal_plans %}

<div class="row">
  <ul class="list-group mt-4">
    {% for meal_plan in meal_plans %}
    <li class="list-group-item list-group-item-success p-5 mb-4">
      <h3>{{ meal_plan.name }}</h3>
      <p>Start Date: {{ meal_plan.start_date }}</p>
      <p>End Date: {{ meal_plan.end_date }}</p>
      <div class="bg-dark row mt-5 mb-2">
        <a
          href="{% url 'meal_plans:add_meal' meal_plan.id %}"
          class="btn btn-success d-block col-sm-3"
          >Add Meal</a
        >

        <a
          href="{% url 'meal_plans:meal_plan_detail' meal_plan.id %}"
          class="btn btn-success d-block col-sm-3 ml-2"
          >View Plan Details</a
        >
        <a
          href="{% url 'meal_plans:meal_plan_update' meal_plan.id %}"
          class="btn btn-success d-block col-sm-3"
          >Update Plan</a
        >
        <a
          href="{% url 'meal_plans:meal_plan_delete' meal_plan.id %}"
          class="btn btn-success d-block col-sm-3"
          >Delete Plan</a
        >
      </div>
    </li>
    {% endfor %}
  </ul>
</div>
{% else %}
<p>No meal plans available.</p>
{% endif %}

<a href="{% url 'meal_plans:meal_plan_create' %}" class="btn btn-outline-light"
  >Create New Meal Plan</a
>
<p></p>
{% endblock %}

meal_plans/templates/meal_plans/meal_plan_update.html
{% extends 'meal_plans/base.html' %} {% block page_header %}
<div class="pb-2 mb-2 border-bottom p-3 bg-dark text-white rounded mt-4">
  <h2>Update Meal Plan</h2>
</div>
{% endblock page_header %} {% block content %} {% load bootstrap5 %}
<form method="post" class="form-control">
  {% csrf_token %} {% bootstrap_form form %}
  <button type="submit" class="btn btn-dark text-light">Update</button>
</form>
{% endblock %}

meal_plans/templates/meal_plans/meal_update.html
{% extends 'meal_plans/base.html' %} {% block page_header %}
<div class="pb-2 mb-2 border-bottom p-3 bg-dark text-white rounded mt-4">
  <h2>Update Meal</h2>
</div>
{% endblock page_header %} {% block content %} {% load bootstrap5 %}
<form method="post" class="form-control">
  {% csrf_token %} {% bootstrap_form form %}

  <button type="submit" class="btn btn-dark text-light">Update</button>
</form>
{% endblock content %}

meal_plans/templates/meal_plans/recipe_delete.html
{% extends 'meal_plans/base.html' %} {% block page_header %}
<div class="row p-4">
  <div class="border-bottom bg-dark text-white text-center p-2 mb-2">
    <h2>Delete Recipes</h2>
  </div>
</div>
{% endblock page_header %} {% block content %}
<div class="bg-dark text-dark">
  <p>Are you sure you want to delete the recipe for {{ meal.name }}?</p>
</div>
<form method="POST">
  {% csrf_token %}
  <button type="submit">Delete</button>
</form>
{% endblock %}

meal_plans/templates/meal_plans/recipe_detail.html
{% extends 'meal_plans/base.html' %} {% block page_header %}
<div class="row">
  <div class="">
    <div class="bg-dark text-white p-2">
      <h2>Recipe Detail</h2>
    </div>

    {% endblock page_header %} {% block content %}

    <div class="col bg-light p-3 m-3">
      <div class="mb-5">
        <h2>{{ recipe.meal.meal_name }}</h2>
        <p><strong>Ingredients:</strong></p>
        <p>{{ recipe.ingredients }}</p>
        <p><strong>Instructions:</strong></p>
        <p>{{ recipe.instructions }}</p>
      </div>
      <div class="d-flex justify-content-between">
        <a
          href="{% url 'meal_plans:recipe_update' recipe_id=recipe.id %}"
          class="btn btn-outline-success"
          >Edit Recipe</a
        >
        <a
          href="{% url 'meal_plans:recipe_delete' recipe_id=recipe.id %}"
          class="btn btn-outline-success"
          >Delete Recipe</a
        >
      </div>
    </div>
    <div class="col p-3 m-3">
      <a
        href="{% url 'meal_plans:meal_list' %}"
        class="btn btn-outline-light d-block"
        >Back to Meal list</a
      >
    </div>
  </div>
</div>

{% endblock %}

meal_plans/templates/meal_plans/recipe_update.html
{% extends 'meal_plans/base.html' %} {% block page_header %}
<div class="row p-4">
  <div class="border-bottom bg-dark text-white text-center p-2 mb-2">
    <h2>Update Recipes</h2>
  </div>
</div>
{% endblock page_header %} {% block content %}

<form method="POST" class="form-control">
  {% csrf_token %} {{ form.as_p }}
  <button type="submit">Save</button>
</form>
{% endblock %}

meal_plans/templates/meal_plans/search.html
{% extends 'meal_plans/base.html' %} {% block page_header %}
<div class="container">
  <div class="row bg-dark text-white text-center mb-5 p-3">
    <h1>Search Meals</h1>
  </div>
  {% endblock page_header %}{% block content %}
  <div class="row">
    <form method="GET" class="form-control p-3 text-center mb-2">
      <input type="text" name="query" placeholder="Enter your search query" />
      <button type="submit">Search</button>
    </form>

    {% if result %}
    <div class="bg-white p-5">
      <h2 class="text-center">Search Results</h2>
      <div>
        <div class="text-center">
          <img
            src="{{ result.recipe.image }}"
            alt="{{ result.recipe.label }}"
            class="img-thumbnail d-block mx-auto"
          />
          <h3>{{ result.recipe.label }}</h3>
        </div>

        <h3>Ingredients</h3>
        <ul>
          {% for ingredient in result.recipe.ingredientLines %}
          <li>{{ ingredient }}</li>
          {% endfor %}
        </ul>

        <h3>Instructions</h3>
        {% for instruction in result.recipe.ingredients %}
        <span>{{ instruction.text }}</span>, {% endfor %}
        <h3>Health Benifits</h3>
        <ul>
          {% for health in result.recipe.healthLabels %}
          <li>{{ health }}</li>
          {% endfor %}
        </ul>

        <h3>Meal Time</h3>
        {% for mealTime in result.recipe.mealType %}
        <p>{{ mealTime }}</p>

        {% endfor %}
      </div>
      <p>
        Need to search again?
        <a href="{% url 'meal_plans:search' %}" class="btn btn-outline-dark"
          >Search</a
        >
      </p>
      <p>
        Need to add it to the meal?
        <a
          href="{% url 'meal_plans:meal_plan_list' %}"
          class="btn btn-outline-dark"
          >Create meal plan</a
        >
      </p>
      {% elif results %}
      <p>
        The recipe you are looking was not found but you can search among the
        following suggestions
      </p>
      <ul>
        {% for result in results %}
        <li>{{ result.recipe.label }}</li>
        {% endfor %}
      </ul>
      {% else %}
      <div class="col">
        <p>Enter the name of the recipe you want to search</p>
      </div>
      {% endif %}{% endblock content %}
    </div>
  </div>
</div>